tor-address:
  name: Network Tor Address
  description: The Tor address for the network interface.
  type: pointer
  subtype: package
  package-id: squeaknode
  target: tor-address
  interface: main
peer-tor-address:
  name: Peer Tor Address
  description: The Tor address for the peer interface.
  type: pointer
  subtype: package
  package-id: squeaknode
  target: tor-address
  interface: peer
lan-address:
  name: Network LAN Address
  description: The LAN address for the network interface.
  type: pointer
  subtype: package
  package-id: squeaknode
  target: lan-address
  interface: main
password:
  type: string
  name: Password
  description: Administrator password for Squeaknode (The username is 'squeaknode-admin')
  nullable: false
  copyable: true
  masked: true
  default:
    charset: "a-z,A-Z,0-9"
    len: 22
bitcoind:
  type: union
  name: Bitcoin Core
  description: The Bitcoin Core node to connect to
  tag:
    id: type
    name: Type
    description: |
      - Internal: The Bitcoin Core service installed to your Embassy
      - Internal Proxy: The Bitcoin Proxy service installed on your Embassy
    variant-names:
      internal: Internal
      internal-proxy: Internal (Bitcoin Proxy)
  default: internal
  variants:
    internal:
      user:
        type: pointer
        name: RPC Username
        description: The username for the RPC user for Bitcoin Core
        subtype: package
        package-id: bitcoind
        target: config
        selector: "$.rpc.username"
        multi: false
      password:
        type: pointer
        name: RPC Password
        description: The password for the RPC user for Bitcoin Core
        subtype: package
        package-id: bitcoind
        target: config
        selector: "$.rpc.password"
        multi: false
    internal-proxy:
      user:
        type: pointer
        name: RPC Username
        description: The username for the RPC user allocated to Squeaknode
        subtype: package
        package-id: btc-rpc-proxy
        target: config
        multi: false
        selector: '$.users.[?(@.name == "squeaknode")].name'
      password:
        type: pointer
        name: RPC Password
        description: The password for the RPC user allocated to Squeaknode
        subtype: package
        package-id: btc-rpc-proxy
        target: config
        multi: false
        selector: '$.users.[?(@.name == "squeaknode")].password'
